# Minimal test config for macro compilation testing
# This file is for testing purposes only

config:
  send_anonymous_usage_stats: false

prophecy-default:
  outputs:
    default:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: test
      password: test
      dbname: test
      schema: test
    target: default
    
    bigquery:
      type: bigquery
      threads: 1
      method: service-account
      project: test-project
      dataset: test_dataset
      keyfile: /dev/null
    target: bigquery
    
    duckdb:
      type: duckdb
      threads: 1
      path: :memory:
      schema: test
    target: duckdb

